spec:
  template:
    metadata:
    spec:
      - image: us.gcr.io/servers-294415/lab-ping/git-ping:078c0d41e76a076cc7ba158314c98a905df332c6
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 512M

traffic:
  - percent: 100
    latestRevision: true
